name: Terraform Validator and Formatter
on:
  pull_request:
    branches:
      - main

jobs:
  tf_version:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - run: terraform validate
        working-directory: ./

      - run: terraform fmt -diff -check -recursive
        working-directory: ./
